// "Languages" accepted by Slack.
module.exports = {
	'auto': 'Auto Detect Type',
	'text': 'Plain Text',
	'applescript': 'AppleScript',
	'boxnote': 'BoxNote',
	'c': 'C',
	'csharp': 'C#',
	'cpp': 'C++',
	'css': 'CSS',
	'csv': 'CSV',
	'clojure': 'Clojure',
	'coffescript': 'CoffeScript',
	'cfm': 'Cold Fusion',
	'd': 'D',
	'dart': 'Dart',
	'diff': 'Diff',
	'dockerfile': 'Docker',
	'erlang': 'Erlang',
	'fsharp': 'F#',
	'fortran': 'Fortran',
	'go': 'Go',
	'groovy': 'Groovy',
	'html': 'HTML',
	'handlebars': 'Handlebars',
	'haskell': 'Haskell',
	'haxe': 'Haxe',
	'java': 'Java',
	'javascript': 'JavaScript/JSON',
	'kotlin': 'Kotlin',
	'latex': 'LaTeX/sTeX',
	'lisp': 'Lisp',
	'lua': 'Lua',
	'markdown': 'Markdown',
	'matlab': 'MATLAB',
	'mumps': 'MUMPS',
	'ocaml': 'OCaml',
	'objc': 'Objective-C',
	'php': 'PHP',
	'pascal': 'Pascal',
	'perl': 'Perl',
	'pig': 'Pig',
	'post': 'Slack Post',
	'powershell': 'Powershell',
	'puppet': 'Puppet',
	'python': 'Python',
	'r': 'R',
	'ruby': 'Ruby',
	'rust': 'Rust',
	'sql': 'SQL',
	'sass': 'Sass',
	'scala': 'Scala',
	'scheme': 'Scheme',
	'shell': 'Shell',
	'smalltalk': 'Smalltalk',
	'swift': 'Swift',
	'tsv': 'TSV',
	'vb': 'VB.NET',
	'vbscript': 'VBScript',
	'velocity': 'Velocity',
	'verilog': 'Verilog',
	'xml': 'XML',
	'yaml': 'YAML'
};
